/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2022-05-30 08:50:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class forgetPassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "addBootstrap.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar2.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Raleway', sans-serif;\r\n");
      out.write("\tbackground-color: #fafafa;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bigBox {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 100px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box1 {\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box2 {\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box3 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 300px;\r\n");
      out.write("\tpadding: 5px 50px 5px 5px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".txt1 {\r\n");
      out.write("\tpadding: 0px 0px 0px 100px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".enter {\r\n");
      out.write("\tpadding : 0px 0px 0px 50px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 50px;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#resetBtn {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 200px;\r\n");
      out.write("\tleft: 190px;\r\n");
      out.write("\t-webkit-appearance: none;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    border-style: solid;\r\n");
      out.write("    border-width: 1px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    line-height: 26px;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    background: #3897f0;\r\n");
      out.write("    border-color: #3897f0;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("input[type='submit']:disabled{\r\n");
      out.write("\tcursor: not-allowed;\r\n");
      out.write("\topacity: .3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#reset {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 200px;\r\n");
      out.write("\tleft: 190px;\r\n");
      out.write("\t-moz-box-shadow: 0px 1px 0px 0px #f0f7fa;\r\n");
      out.write("\t-webkit-box-shadow: 0px 1px 0px 0px #f0f7fa;\r\n");
      out.write("\tbox-shadow: 0px 1px 0px 0px #f0f7fa;\r\n");
      out.write("\tbackground:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #33bdef), color-stop(1, #019ad2));\r\n");
      out.write("\tbackground:-moz-linear-gradient(top, #33bdef 5%, #019ad2 100%);\r\n");
      out.write("\tbackground:-webkit-linear-gradient(top, #33bdef 5%, #019ad2 100%);\r\n");
      out.write("\tbackground:-o-linear-gradient(top, #33bdef 5%, #019ad2 100%);\r\n");
      out.write("\tbackground:-ms-linear-gradient(top, #33bdef 5%, #019ad2 100%);\r\n");
      out.write("\tbackground:linear-gradient(to bottom, #33bdef 5%, #019ad2 100%);\r\n");
      out.write("\tfilter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#33bdef', endColorstr='#019ad2',GradientType=0);\r\n");
      out.write("\tbackground-color:#33bdef;\r\n");
      out.write("\t-moz-border-radius:6px;\r\n");
      out.write("\t-webkit-border-radius:6px;\r\n");
      out.write("\tborder-radius:6px;\r\n");
      out.write("\tborder:1px solid #057fd0;\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tcolor:#ffffff;\r\n");
      out.write("\t\r\n");
      out.write("\tfont-size:10px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tpadding:7px 24px;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\ttext-shadow:0px 1px 0px #5b6178;\r\n");
      out.write("}\r\n");
      out.write("#reset:hover {\r\n");
      out.write("\tbackground:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #019ad2), color-stop(1, #33bdef));\r\n");
      out.write("\tbackground:-moz-linear-gradient(top, #019ad2 5%, #33bdef 100%);\r\n");
      out.write("\tbackground:-webkit-linear-gradient(top, #019ad2 5%, #33bdef 100%);\r\n");
      out.write("\tbackground:-o-linear-gradient(top, #019ad2 5%, #33bdef 100%);\r\n");
      out.write("\tbackground:-ms-linear-gradient(top, #019ad2 5%, #33bdef 100%);\r\n");
      out.write("\tbackground:linear-gradient(to bottom, #019ad2 5%, #33bdef 100%);\r\n");
      out.write("\tfilter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#019ad2', endColorstr='#33bdef',GradientType=0);\r\n");
      out.write("\tbackground-color:#019ad2;\r\n");
      out.write("}\r\n");
      out.write("#reset:active {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-fluid bigBox\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-1\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t<div class=\"box2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box3\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"txt1\">Reset Password</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"txt1\">We can help you reset your password using the email address linked to your LifeX account.</p>\r\n");
      out.write("\t\t\t\t\t<form action=\"resetServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"enter\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"color:red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<b>Enter Email</b> &nbsp;&nbsp;&nbsp;<input id=\"message\" type=\"text\" name=\"resetPassword\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" id=\"resetBtn\" name=\"resetBtn\" value=\"Reset Password\" >\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t$('#resetBtn').attr('disabled',true);\r\n");
      out.write("\t$('#message').keyup(function(){\r\n");
      out.write("\t  if($(this).val().length !=0)\r\n");
      out.write("\t      $('#resetBtn').attr('disabled', false);            \r\n");
      out.write("\t  else\r\n");
      out.write("\t      $('#resetBtn').attr('disabled',true);\r\n");
      out.write("\t})\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
