/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2022-06-09 11:55:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.User;

public final class HomePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/homePageCSS.css\" type=\"text/css\"></link>\r\n");
      out.write("\t\r\n");
      out.write("\t");
User myUser = (User) session.getAttribute("User_Info");
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "addBootstrap.jsp", out, false);
      out.write("\r\n");
      out.write("\t<title>Home</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t@charset \"ISO-8859-1\";\r\n");
      out.write("\t\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tbackground-color: #FFF9ED !important; \r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t::-webkit-scrollbar {\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.col-md-12 >.text-center {\r\n");
      out.write("\t\tfont-family: 'Josefin Sans', sans-serif;\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.container-fluid .row .text-center {\r\n");
      out.write("\t\tpadding: 17px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.container-fluid .row .text-center .shadowBox > h4 {\r\n");
      out.write("\t\tfont-family: 'Yanone Kaffeesatz', sans-serif;\r\n");
      out.write("\t\tfont-size: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.container-fluid .row .text-center .shadowBox > h6 {\r\n");
      out.write("\t\tfont-family: 'Quicksand', sans-serif;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#second {\r\n");
      out.write("\t\tbackground-image: url(images/pexels-photo-1122405.jpeg);\r\n");
      out.write("\t\tbackground-size: auto;\r\n");
      out.write("\t\tbackground-position: center center;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tpadding: 30px;\r\n");
      out.write("\t\tborder-radius: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.shadowBox:hover {\r\n");
      out.write("\t\tbackground: rgba(0, 0, 0, 0.7);\r\n");
      out.write("\t\tborder-radius: 10px;\r\n");
      out.write("\t\ttransition: background 1s ease-in-out;\r\n");
      out.write("\t\tborder: 2px solid white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#facebook {\r\n");
      out.write("\t\tpadding: 2rem;\r\n");
      out.write("\t\tfont-size: 4.5em;\r\n");
      out.write("\t\tcolor: #3B5998; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#twitter {\r\n");
      out.write("\t\tpadding: 2rem;\r\n");
      out.write("\t\tfont-size: 4.5em;\r\n");
      out.write("\t\tcolor: #00ACED;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#snapchat {\r\n");
      out.write("\t\tpadding: 2rem;\r\n");
      out.write("\t\tfont-size: 4.5em;\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#instagram {\r\n");
      out.write("\t\tpadding: 2rem;\r\n");
      out.write("\t\tfont-size: 4.5em;\r\n");
      out.write("\t\tcolor: #c32aa3;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#youtube {\r\n");
      out.write("\t\tpadding: 2rem;\r\n");
      out.write("\t\tfont-size: 4.5em;\r\n");
      out.write("\t\tcolor: #BB0000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#twitter:hover, #instagram:hover{\r\n");
      out.write("\t\ttransition: color 0.5s ease;\r\n");
      out.write("\t\tcolor: #fd1d1d;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#facebook:hover, #snapchat:hover, #youtube:hover{\r\n");
      out.write("\t\ttransition: color 0.5s ease;\r\n");
      out.write("\t\tcolor: #fc466b;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");

response.setHeader("Cache-Control","no-cache, no-store, must-revalidate"); //HTTP 1.1
response.setHeader("Pragma", "no-cache"); //HTTP 1.0
response.setHeader("Expires", "0"); //Proxies

if (session.getAttribute("username") == null) {
	request.getRequestDispatcher("Login.jsp").forward(request, response);	
}


      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-- Description -->\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\" style=\"padding-top: 50px;\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h1 class=\"text-center\" style=\"font-family: 'Pacifico', cursive;\">Welcome To LifeX, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </h1>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"openRequest\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<p style=\"color: red; font-weight: bold;\">You have \r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalRequest}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"btnSubmit\"> friend requests</p>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"logoutServlet\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"logout\" value=\"Logout\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-center\">LifeX is an Intellectual, All-In-One Web-Application that aids Teenagers' to improve their Life Management Skills.</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 text-center\" id=\"second\">\r\n");
      out.write("\t\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 shadowBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"image\" onclick=\"form.action='RedirectFriends';\" src=\"images/applouse-xxl.png\" style=\"max-width: 25%; height: auto;\">\r\n");
      out.write("\t\t\t\t\t\t<h4>#Friends @Huei Ming</h4>\r\n");
      out.write("\t\t\t\t\t\t<h6><strong>Connect</strong> with people around you</h6>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<!-- Connect -->\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 text-center\" style=\"padding: 10px;\">\r\n");
      out.write("\t\t\t\t\t<h1 style=\"font-family: 'Pacifico', cursive;\">Connect With Us</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 text-center\" style=\"padding: 10px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\" id=\"facebook\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\" id=\"twitter\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-snapchat\" id=\"snapchat\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-instagram\" id=\"instagram\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-youtube\" id=\"youtube\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
